### ISSUE TITLE
Doubts about Location in CFG.POS_PRED

### ISSUE THREAD

**Issue by AzulYang** [object-understanding/SLASH#1]
I find that the LOCATION in cfg is [1,2,3],and in _model.py_there are some judgment statements, such as https://github.com/object-understanding/SLASH/blob/b17da22a1bf3ec40bcc78434221f9052e1c42800/model.py#L310.Can you give me some suggestions on this?
Another,I want to train on unsupervised caused I got all prediction labels,what parts of the code need to be modified?Thanks a lot.

**Comment by AzulYang** [comment]
I feel excited about the upcoming release of the new version code and look forward to it very much. Regarding the second question, my expression may not be clear. I would like to use the IPPE module in my own work and in other datasets.Because you are using weak-supervised and only a small portion of labels are used, I want to use all of them.  Labels is what I predicted and not from the groundtruth.

**Comment by object-understanding** [comment]
For that case, in this version, you can utilize full sup. with cfg setting:
- WEAK_SUP.RANDOM_PROP: 1.0
- WEAK_SUP.SPLIT.RATIO: 1.0
- WEAK_SUP.SPLIT.TRAIN.BATCH_FUSION_RATIO: 1.0

By the way, as we found some errors in this version about the Hungarian matching, so please keep that in you mind!

**Comment by AzulYang** [comment]
Yes, I also encountered problems when using the Hungarian matching, and I will pay attention to errors,and I found that these errors can lead to training failed.Regarding Locations, is it like Savi ,which provides some initialization in the first few slot iteration?

**Comment by object-understanding** [comment]
Sorry for our late reply.

Firstly, we're happy to let you know that our new version of the code is now committed with cleansing codes that are not necessary for now including removing LOCATIONS.

And secondly, unlike that we said our Hungarian matching has errors, we checked that our matching algorithm has no problem and the training process of IPPE and SA-SW (SAVi-like model) also has no problem.

So, it would be grateful if you check our new version of code, and if you have any additional problem please feel free to add a comment!
